### ISSUE TITLE
Can't scroll servers

### ISSUE THREAD

**Issue by gibby9er9er0** [SlippingGittys-Discord-Themes/Diskette#10] opened 2024-07-12 03:31 UTC
Using the latest version of Vencord I decided to try some themes and Diskette was among them and I love it! However its currently unusable as there is no way for me to scroll through the servers I'm in as mouse scroll doesn't do anything

**Comment by ghost** [comment] 2024-07-15 20:50
hello @gibby9er9er0 is this still an issue after 768e8e7? please check using the latest theme css, explanation on how to use it is in the readme

**Comment by ghost** [comment] 2024-07-16 10:48
i'm not able to reproduce this after my last commits so i'll close this issue. please make a comment if it still persists

**Closed as completed by ghost** 2024-07-16 10:48 UTC
